### ISSUE TITLE
[Search Service] Integration in Docker Compose Entwicklungsumgebung

### ISSUE THREAD

**Issue by TMogdans** [TMogdans/bsk#19]
## Beschreibung
Integration des Search Service und der benötigten Elasticsearch-Instanz in die Docker Compose-Entwicklungsumgebung für lokale Entwicklung und Tests.

## Aufgaben
- [ ] Erstellung eines Dockerfiles für den Search Service (Entwicklungsumgebung)
- [ ] Konfiguration einer Elasticsearch-Instanz im Docker Compose Setup
- [ ] Integration des Search Service in die docker-compose.yml
- [ ] Konfiguration der notwendigen Umgebungsvariablen (NATS-Verbindung, Elasticsearch-Verbindung)
- [ ] Einrichtung der Abhängigkeiten zwischen den Services
- [ ] Erstellen von Entwicklungsskripten für schnelles Setup
- [ ] Volume-Mapping für lokale Entwicklung
- [ ] Hot-Reload-Konfiguration für Entwicklungsfreundlichkeit

## Environment-Konfiguration
```yaml
# Beispiel für docker-compose.yml Erweiterung
search-service:
  build:
    context: .
    dockerfile: services/search-service/deployment/development/Dockerfile
  container_name: search-service
  restart: unless-stopped
  depends_on:
    elasticsearch:
      condition: service_healthy
    nats:
      condition: service_started
  environment:
    NODE_ENV: development
    PORT: 3000
    LOG_LEVEL: debug
    ELASTICSEARCH_NODE: http://elasticsearch:9200
    NATS_SERVER: nats:4222
    # Weitere benötigte Umgebungsvariablen
  ports:
    - "3015:3000"
  volumes:
    - ./services/search-service/api:/app/services/search-service/api
  networks:
    - bsk-network
  command: ["pnpm", "run", "dev"]

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
  container_name: elasticsearch
  environment:
    - node.name=elasticsearch
    - cluster.name=es-docker-cluster
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  networks:
    - bsk-network
  healthcheck:
    test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.:"green"\|status.:"yellow"'"]
    interval: 10s
    timeout: 10s
    retries: 5
```

## Akzeptanzkriterien
- Der Search Service startet fehlerfrei in der Docker Compose-Umgebung
- Elasticsearch ist konfiguriert und kann vom Search Service erreicht werden
- Der Search Service kann Events von NATS empfangen
- Die Entwicklungsumgebung unterstützt Hot-Reload für schnelle Codeänderungen
- Die Integration ist dokumentiert und neue Entwickler können sie leicht nutzen
- Die Suchfunktionalität kann in der Entwicklungsumgebung getestet werden
