### ISSUE TITLE
[Auth Service] Integration in Docker Compose Entwicklungsumgebung

### ISSUE THREAD

**Issue by TMogdans** [TMogdans/bsk#29]
## Beschreibung
Integration des Authentication & Identity Service in die Docker Compose-Entwicklungsumgebung für lokale Entwicklung und Tests.

## Aufgaben
- [ ] Erstellung eines Dockerfiles für den Authentication & Identity Service (Entwicklungsumgebung)
- [ ] Konfiguration des Identity Management Systems (Keycloak) in Docker Compose
- [ ] Integration des Auth Services in die docker-compose.yml
- [ ] Konfiguration der notwendigen Umgebungsvariablen und Abhängigkeiten
- [ ] Einrichtung der Datenbankintegration und Persistenz
- [ ] Konfiguration der Netzwerkintegration für Service-zu-Service-Kommunikation
- [ ] Erstellen von Entwicklungsskripten für schnelles Setup und Initialisierung
- [ ] Hot-Reload-Konfiguration für entwicklerfreundliches Arbeiten

## Environment-Konfiguration
```yaml
# Beispiel für docker-compose.yml Erweiterung
auth-service:
  build:
    context: .
    dockerfile: services/auth-service/deployment/development/Dockerfile
  container_name: auth-service
  restart: unless-stopped
  depends_on:
    postgres:
      condition: service_healthy
    keycloak:
      condition: service_healthy
  environment:
    NODE_ENV: development
    PORT: 3000
    LOG_LEVEL: debug
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: auth_service
    DB_USER: postgres
    DB_PASSWORD: S3cret
    KEYCLOAK_URL: http://keycloak:8080/auth
    KEYCLOAK_REALM: boardgame-platform
    KEYCLOAK_CLIENT_ID: auth-service
    KEYCLOAK_CLIENT_SECRET: your-secret-here
  ports:
    - "3020:3000"
  volumes:
    - ./services/auth-service/api:/app/services/auth-service/api
    - node_modules_auth:/app/services/auth-service/api/node_modules
  networks:
    - bsk-network
  command: ["pnpm", "run", "dev"]
```

## Akzeptanzkriterien
- Der Authentication Service startet fehlerfrei in der Docker Compose-Umgebung
- Das Identity Management System (Keycloak) ist konfiguriert und erreichbar
- Die Datenbankintegration funktioniert korrekt mit Persistenz zwischen Neustarts
- Der Service kann von anderen Services in der Entwicklungsumgebung erreicht werden
- Die Entwicklungsumgebung unterstützt Hot-Reload für schnelle Codeänderungen
- Eine initiale Konfiguration (Basis-Rollen, Admin-Benutzer) wird automatisch eingerichtet
- Die Integration ist dokumentiert und neue Entwickler können sie leicht nutzen
