### ISSUE TITLE
[Auth Service] Kubernetes Deployment für Produktionsumgebung

### ISSUE THREAD

**Issue by TMogdans** [TMogdans/bsk#30]
## Beschreibung
Konfiguration und Bereitstellung des Authentication & Identity Service in der Kubernetes-Produktionsumgebung mit Fokus auf Sicherheit, Skalierbarkeit und Hochverfügbarkeit.

## Aufgaben
- [ ] Erstellung eines Dockerfiles für den Auth Service (Produktion)
- [ ] Entwicklung von Kubernetes-Deployment-Manifesten für den Auth Service
- [ ] Konfiguration des Identity Management Systems in Kubernetes
- [ ] Erstellung von ConfigMaps für die Service-Konfiguration
- [ ] Definieren von Secret-Objekten für sensible Konfigurationen
- [ ] Implementierung von Health-Checks und Readiness/Liveness Probes
- [ ] Konfiguration von Resource Limits und Requests
- [ ] Einrichtung von horizontaler Skalierung (HPA)
- [ ] Konfiguration der Persistent Storage für Benutzerdaten
- [ ] Integration in den bestehenden Ingress für API-Zugriff
- [ ] Implementierung von Network Policies für erhöhte Sicherheit
- [ ] Backup- und Recovery-Strategie für kritische Identitätsdaten

## Deployment-Manifest-Beispiel
```yaml
# services/auth-service/deployment/production/k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: bsk
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ${DOCKER_REGISTRY}/auth-service:${VERSION}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: auth-service-environment-config-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-environment-config-map
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-service-environment-config-map
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auth-service-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-db-credentials
              key: password
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: auth-service-environment-config-map
              key: KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: auth-service-environment-config-map
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: auth-service-environment-config-map
              key: KEYCLOAK_CLIENT_ID
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-keycloak-credentials
              key: client-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
```

## Erweiterte Sicherheitsanforderungen
- Verschlüsselte Kommunikation zwischen allen Komponenten
- Regelmäßige Rotation der Zugriffsschlüssel und Secrets
- Audit-Logging für alle administrativen Aktionen
- Netzwerksegmentierung mit strikten Network Policies
- Pod Security Policies für erhöhte Container-Sicherheit
- Regelmäßige Backup-Strategie für Identity-Daten

## Akzeptanzkriterien
- Der Authentication & Identity Service ist erfolgreich in Kubernetes deployed
- Das Identity Management System läuft stabil mit persistenten Daten
- Die Integration mit anderen Services funktioniert zuverlässig
- Der Service skaliert bei erhöhter Last automatisch
- Die Sicherheitsmaßnahmen sind implementiert und getestet
- Die API ist über Ingress erreichbar und angemessen abgesichert
- Ressourcenlimits sind angemessen konfiguriert
- Alle Secrets werden sicher verwaltet
- Eine Backup- und Recovery-Strategie ist implementiert und getestet
